---
# Used to speed up Vagrant-based installs by copying packages locally
# Installs packages from a synced Vagrant folder
# Assumes amd64 packages
# Files will be copied to your Vagrant shared installers folder if not present


- name: Set Python3 download filename
  set_fact:
    python3_installer_filename: "Python-{{ python3_version }}.tar.xz"

#####
#  Debian specific install stuff
#####

# Ensure installer is local
- name: Check for local installer
  stat: path=/home/vagrant/shared/installers/{{ python3_installer_filename }}
  register: python3_installer_filepath
  when: ansible_os_family == "Debian"

- name: Get installer if not present (Vagrant with Debian)
  get_url:
  get_url:
    url: https://www.python.org/ftp/python/{{ python3_version }}/Python-{{ python3_version }}.tar.xz
    dest: /home/vagrant/shared/installers/{{ python3_installer_filename }}
  when: python3_installer_filepath.stat.exists == false and ansible_os_family == "Debian"

######
##  Redhat specific install stuff
######

###

- name: Unarchive installer
  unarchive:
    src: /home/vagrant/shared/installers/{{ python3_installer_filename }}
    dest: /tmp
    copy: no

- name: Set source directory for extracted source files
  set_fact:
    python3_source_dir: "/tmp/Python-{{ python3_version }}"

- name: Get build dependencies
  shell: sudo apt-get -y build-dep python3.4
  args:
    chdir: "{{ python3_source_dir }}"

- name: Configure
  shell: ./configure
  args:
    chdir: "{{ python3_source_dir }}"

- name: make
  shell: make
  args:
    chdir: "{{ python3_source_dir }}"

# Working around the failing test_ssl test
#- name: make test
#  shell: make test
#  args:
#    chdir: "{{ python3_source_dir }}"

- name: make install
  shell: make install
  args:
    chdir: "{{ python3_source_dir }}"